// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minder.DataAccess.Context;

namespace Minder.DataAccess.Migrations
{
    [DbContext(typeof(MinderContext))]
    [Migration("20210526190353_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Minder.DataAccess.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("Minder.DataAccess.Models.DeviceMetadatum", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("MetadataId")
                        .HasColumnType("int");

                    b.HasIndex("DeviceId");

                    b.HasIndex(new[] { "MetadataId", "DeviceId" }, "IX_DeviceMetadata")
                        .IsUnique();

                    b.ToTable("DeviceMetadata");
                });

            modelBuilder.Entity("Minder.DataAccess.Models.DevicePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentDevicePartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ParentDevicePartId");

                    b.ToTable("DevicePart");
                });

            modelBuilder.Entity("Minder.DataAccess.Models.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceType");
                });

            modelBuilder.Entity("Minder.DataAccess.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Minder.DataAccess.Models.EquipmentDevicePart", b =>
                {
                    b.Property<int>("DevicePartId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasIndex("DevicePartId");

                    b.HasIndex(new[] { "EquipmentId", "DevicePartId" }, "IX_EquipmentDevicePart")
                        .IsUnique();

                    b.ToTable("EquipmentDevicePart");
                });

            modelBuilder.Entity("Minder.DataAccess.Models.Metadatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("Minder.DataAccess.Models.Device", b =>
                {
                    b.HasOne("Minder.DataAccess.Models.DeviceType", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeId")
                        .HasConstraintName("FK_Device_DeviceType")
                        .IsRequired();

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("Minder.DataAccess.Models.DeviceMetadatum", b =>
                {
                    b.HasOne("Minder.DataAccess.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("FK_DeviceMetadata_Device")
                        .IsRequired();

                    b.HasOne("Minder.DataAccess.Models.Metadatum", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId")
                        .HasConstraintName("FK_DeviceMetadata_Metadata")
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Minder.DataAccess.Models.DevicePart", b =>
                {
                    b.HasOne("Minder.DataAccess.Models.Device", "Device")
                        .WithMany("DeviceParts")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("FK_DevicePart_Device")
                        .IsRequired();

                    b.HasOne("Minder.DataAccess.Models.DevicePart", "ParentDevicePart")
                        .WithMany("InverseParentDevicePart")
                        .HasForeignKey("ParentDevicePartId")
                        .HasConstraintName("FK_DevicePart_DevicePart1");

                    b.Navigation("Device");

                    b.Navigation("ParentDevicePart");
                });

            modelBuilder.Entity("Minder.DataAccess.Models.EquipmentDevicePart", b =>
                {
                    b.HasOne("Minder.DataAccess.Models.DevicePart", "DevicePart")
                        .WithMany()
                        .HasForeignKey("DevicePartId")
                        .HasConstraintName("FK_EquipmentDevicePart_DevicePart")
                        .IsRequired();

                    b.HasOne("Minder.DataAccess.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .HasConstraintName("FK_EquipmentDevicePart_Equipment")
                        .IsRequired();

                    b.Navigation("DevicePart");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Minder.DataAccess.Models.Device", b =>
                {
                    b.Navigation("DeviceParts");
                });

            modelBuilder.Entity("Minder.DataAccess.Models.DevicePart", b =>
                {
                    b.Navigation("InverseParentDevicePart");
                });

            modelBuilder.Entity("Minder.DataAccess.Models.DeviceType", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
